### ISSUE TITLE
Running 'run_ancient.sh'

### ISSUE THREAD

**Issue by KishoreChopra** [ekirving/mesoneo_paper#2]
Hi,
if I want to estimate allele frequency trajectories using only aDNA, can I only use the file under "ancestral_paths_v3:"?
Do I need to include modern groups in my file? Are there any other considerations or points to keep in mind?

**Comment by ekirving** [comment]
If all you want to do is infer frequency trajectories using only aDNA then you don't need my pipeline, and you would be better off using CLUES directly. See https://github.com/standard-aaron/clues/wiki/Command-line-options-for-CLUES for documentation.

**Comment by KishoreChopra** [comment]
Thank you very much !!!
